export enum FactionFlag {
  InviteMember = 1,
  EditMember = 2,
  RemoveMember = 3,
  BlockChat = 4,
  GovernmentAdvertisement = 5,
  HQ = 6,
  Storage = 7,
  RemoveAllBarriers = 8,
  Uniform = 9,
  SWAT = 10,
  UPR = 11,
  WeaponLicense = 12,
  FireManager = 13,
  RespawnVehicles = 14,
  ManageVehicles = 15,
};