export enum StaffFlag {
  Events = 1,
  Doors = 2,
  Factions = 4,
  FactionsStorages = 5,
  Properties = 6,
  Spots = 7,
  Blips = 8,
  CK = 10,
  GiveItem = 11,
  CrackDens = 12,
  TruckerLocations = 13,
  Furnitures = 14,
  Animations = 15,
  Companies = 16,
  Items = 18,
  VehicleMaintenance = 19,
  Drugs = 20,
};